### ISSUE TITLE
minclient: Calling `Client.SendPacket()` from a callback will deadlock.

### ISSUE THREAD

**Issue by Yawning** [katzenpost/minclient#1]
I'm not sure if this should be an allowed operation or not.  If not, then this should be documented clearly, otherwise the callbacks need to be called from a separate go routine that isn't the connection worker.

**Comment by Yawning** [comment]
This is also a problem that applies if SendPacket is called while a callback is being dispatched, which means this absolutely needs to be fixed.

**Comment by david415** [comment]
from my audit of the code it seems like this bug was fixed in 63be5c6ebedc437b012c31934cdf695710337622
